export const CITY_DATA = [
  { id: "01", value: "서울" },
  { id: "02", value: "부산" },
  { id: "03", value: "대구" },
  { id: "04", value: "인천" },
  { id: "05", value: "광주" },
  { id: "06", value: "대전" },
  { id: "07", value: "울산" },
  { id: "08", value: "경기" },
  { id: "09", value: "강원" },
  { id: "10", value: "충북" },
  { id: "11", value: "충남" },
  { id: "12", value: "전북" },
  { id: "13", value: "전남" },
  { id: "14", value: "경북" },
  { id: "15", value: "경남" },
  { id: "16", value: "제주" },
  { id: "17", value: "세종" },
];
